name: Deploy to Prod

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version '
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      VERSION: ${{ github.event.inputs.version }}
      REGISTRY: cr.yandex/${{ secrets.YCR_REGISTRY_ID }}
    steps:
      - name: Check Docker image exists
        run: |
          docker pull $REGISTRY/app:${VERSION}_latest

      - name: SSH into VM and run Docker
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker pull $REGISTRY/app:${VERSION}_latest
            docker stop app || true
            docker rm app || true
            docker run -d --name app -p 80:3000 $REGISTRY/app:${VERSION}_latest

      - name: Comment on Issue
        run: |
          echo "Released version ${VERSION} to production" >> deploy-comment.txt
          echo "Date: $(date)" >> deploy-comment.txt
          echo "By: $GITHUB_ACTOR" >> deploy-comment.txt
